name: Close linked issues on merge

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Close referenced issues
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body;
            const issueNumbers = [...body.matchAll(/(?:Closes|Fixes)\s+#(\d+)/gi)].map(match => match[1]);

            for (const number of issueNumbers) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(number),
                state: "closed"
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(number),
                body: "✅ This issue was automatically closed because the pull request was merged."
              });
            }
