name: Deploy storybook-static to GitHub Pages

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Enable Corepack & Use pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Storybook
        run: pnpm run build:storybook

      - name: Setup GitHub Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v5

      - name: Upload Storybook artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./apps/docs/storybook-static"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
